services:
  - type: web
    name: rag-based-mutual-fund-faq-chatbot
    runtime: python
    pythonVersion: "3.11.11"
    buildCommand: pip install -r requirements.txt && python code/ingest.py
    startCommand: streamlit run code/ui/app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
